package com.fleetbite.order.domain.model;

public enum OrderHistoryEventType {
	ORDER_CREATED,
	ORDER_CONFIRMED,
	ORDER_PREPARING,
	ORDER_READY,
	ORDER_WAITING_FOR_DRIVER,
	ORDER_CANCELLED,
	DRIVER_ASSIGNED,
	ASSIGNMENT_ACCEPTED,
	ASSIGNMENT_REJECTED,
	ORDER_PICKED_UP,
	ORDER_IN_TRANSIT,
	ORDER_DELIVERED
}
